### ISSUE TITLE
str type error

### ISSUE THREAD

**Issue by durack1** [pochedls/xagg#1]
```
(xagg) duro@ocean:[xagg]:[master]:[11621]> ./xagg.py --outputDirectory ~tmp > log.txt
Traceback (most recent call last):
  File "./xagg.py", line 137, in <module>
    fx.createLookupDictionary(diskPaths, outfile=cmipMetaFile)
  File "~git/xagg/fx.py", line 621, in createLookupDictionary
    key = mip_era + '.' + cmipTable + '.' + variable
TypeError: can only concatenate list (not "str") to list
```

**Comment by pochedls** [comment]
@durack1 I understand the issue. This function (createLookupDictionary) takes in a bunch of paths and creates a lookup dictionary file using the mip_era, table, and variable as keys, which yield the frequency, realm, and dimensions (which would otherwise need to be looked up in the CMOR tables). 

I did this as a one off using paths that were already in the sqlite database. When I added this into the xagg main file a couple days ago, the paths came from the disks (not the database), which meant there were some bad paths. This function tripped on:

`/p/css03/cmip5_css01/data/cmip5/output1/CNRM-CERFACS/CNRM-CM5-2/historical/mon/ocean/Omon/r1i1p1/v20130401/tauucorr/bad0/`

I'll push a fix.
