### ISSUE TITLE
HighResMIP

### ISSUE THREAD

**Issue by lee1043** [pochedls/xagg#19]
Hi @durack1 @pochedls @gleckler1,

I see HighResMIP data is available in the PCMDI scratch at `/p/css03/esgf_publish/CMIP6/HighResMIP`, wondering if xml aggregation for the 'HighResMIP' can be added if it is easy enough. @gleckler1 and I are going help Cheng analyzing diurnal cycle of pr for HighResMIP, and I think it would be very helpful if we can have xmls for those data.

Thanks for your consideration.

**Comment by durack1** [comment]
@lee1043 weird, that wasn’t a MIP that was prioritized for download.

@painter1 can you shed some light on these files and the plan for HighResMIP replication?

**Comment by pochedls** [comment]
@lee1043 - could you let me know what experiments, variables, and frequencies need to be added?

**Comment by lee1043** [comment]
@pochedls thank you for following up.

Experiments:
- control-1950
- highres-future
- highresSST-future
- highresSST-present
- hist-1950
- spinup-1950

Variables: pr

Frequencies: 1 hr, 3 hr, 6 hr, daily if possible

**Comment by durack1** [comment]
@taylor13 this was the query we mentioned in the chat

**Comment by taylor13** [comment]
Hi @painter1 et al.,
We should probably try to begin better prioritizing what data we download.  Perhaps Jeff can say what current priorities he is aware of, and then we can decide what additional data we should move up the list for replication.  Like @durack1 , I'm a little surprised that lots of fields are being downloaded from highresmip experiments.  A single 2-d field like precip. shouldn't be an issue, but I don't think there will be much demand for this data, so filling up our disks with it doesn't seem particularly a good use of resources.  Would be happy to hear other views.

**Comment by gleckler1** [comment]
@taylor13 As far as I know, nobody in-house requested these data, but they will get used.   Maybe Jeff is downloading these data because he is on top of the prioritized list?

**Comment by taylor13** [comment]
when I said I didn't think there would be much demand for "this data", I definitely wasn't referring to precip.  But there are lots of fields that I'm guessing are of interest to only a few, but hopefully there will some interest in every variable from at least one person.

**Comment by durack1** [comment]
@gleckler1 an issue is that there is finite storage, with ~10PB the limit, this houses CMIP6, E3SM, CMIP5, CMIP3 etc so my concern is we fill up and then run out of storage for the very data that is the high priority, frequently requested/downloaded stuff. What happens then, the whole 0.3PB HighResMIP archive is purged?

**Comment by pochedls** [comment]
@lee1043 - when the dust settles on this conversation, could you add a pull request modeled on [this cron job](https://github.com/pochedls/xagg/blob/master/cron/xagg_pr3h_cron.sh). I have your other high temporal resolution runs running on Saturday night and Sunday night. We could install this one on Friday?

**Comment by lee1043** [comment]
@pochedls thank you for following up. I don't think it needs to be very frequent, probably just once in 2 weeks is still fine. Any day is fine with me. I think I am not getting clear idea how to make modification on the cron job, could you please help?

**Comment by durack1** [comment]
@lee1043 this should be helpful https://github.com/pochedls/xagg/blob/master/xagg.py#L51-L81

**Comment by pochedls** [comment]
@lee1043 - I created a cronjob for this that should run Fridays. Could you see if it worked (next Monday by checking the xmls) and re-open this ticket if there were problems?

**Comment by painter1** [comment]
I just discovered this thread buried among lots of other email which I hadn’t read.  I’m sorry I missed it!

I have very simple criteria for getting data.  Detailed prioritization, e.g. by variable, isn’t practical given the volume of data involved.  I’m not currently worried about this sort of issue because we’re not near the capacity of CSS-03 yet.   With the present settings, the main constraint is the bandwidth offered by the data nodes which serve CMIP-6 data.  Even so, we seem to be catching up, i.e. close to hosting all that exists, within the scope of the present settings.

What are the present settings?  If it’s mentioned here:
https://docs.google.com/spreadsheets/d/1H2qXofwjOpCospDcj9LRokpz0HGysRcDK2HmNSJoqyk/edit#gid=771285794
then get it.  If the time frequency is monthly or slower, then get it.  If the data node is known to be a good performer and the time frequency is day or 6hr (but not 6hrLev table), then get it.

That’s all.  I’d welcome ideas for improvement as long as they don’t greatly increase complexity, and there is some consideration given to non-LLNL users (DOE paid for CSS-03 as a national or global server).

**Comment by pochedls** [comment]
@lee1043 - I ran this today, so you should be able to see the xml files.

**Comment by lee1043** [comment]
@pochedls @painter1 thank you very much for help, I sincerely appreciate!
